name: lab
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - mamba==1.0.0
  - conda
  - pip
  - ca-certificates
  - certifi
  - openssl
  - jupyterlab
  - nodejs
  - panel # needs to be in base to connect to widgets, not sure iff it has to be from pyviz channel
  - nb_conda_kernels
  - ipykernel
  # - ipywidgets # jupyterlab_widgets here and ipywidgets in project env
  - ipyleaflet
  - voila
  - jupyterlab_code_formatter
    # - jupyterlab_vim  # for vim users ^^
  - jupyterlab_widgets
  - jupyter-resource-usage
  - jupyter-panel-proxy # not sure if this one is really useful
  - jupyterlab-lsp # breaks tab complete if python-lsp-server not installed
  - python-lsp-server
    # - jupyterlab-git  # causes warning when git not on os
    # - jupyterlab_execute_time # breaks env on windows installation
  - dask-labextension
  - jupyterlab-spellchecker
  - nbgitpuller
  # - lckr-jupyterlab-variableinspector  # doesn't work on my machine yet
  - black
  - isort
  - gh-scoped-creds # check if useful
  - nbstripout
